version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy
    overwrite: yes
hooks:
  AfterInstall:
    - location: stop.sh # nginx 와 연결되지 않은 스프링 부트 종료.
      timeout: 60
  ApplicationStart:
    - location: start.sh # nginx 와 연결되어 있지 않은 포트로 스프링 부트 시작.
      timeout: 60
  ValidateService:
    - location: health.sh # 새 서비스 health check
      timeout: 60
